name: Flutter Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip and Move Files
        run: |
          unzip project.zip -d temp_folder
          ROOT_DIR=$(find temp_folder -name "lib" -exec dirname {} \;)
          cp -R $ROOT_DIR/* .
          rm -rf temp_folder

      - name: Fix Pubspec Immediately
        run: |
          cat <<EOF > pubspec.yaml
          name: my_app
          description: Webview app
          version: 1.0.0+1
          publish_to: 'none'
          environment:
            sdk: ">=2.17.0 <4.0.0"
          dependencies:
            flutter:
              sdk: flutter
            webview_flutter: ^4.2.2
            permission_handler: ^10.2.0
          flutter:
            uses-material-design: true
            assets:
              - assets/
          EOF

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Recreate Android Project
        run: |
          rm -rf android
          flutter create . --platforms android --org com.yourname.app

      - name: Add Permissions to AndroidManifest
        run: |
          # הזרקת הרשאות לקובץ המניפסט
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.RECORD_AUDIO" />\n    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />' android/app/src/main/AndroidManifest.xml

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        # כאן הגדרנו את ה-min-sdk ישירות בפקודה כדי לתמוך באנדרואיד 8.1 ומעלה
        run: flutter build apk --release --no-tree-shake-icons --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-release
          path: build/app/outputs/flutter-apk/*.apk
