name: Flutter Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # עודכן ל-v4

      - name: Unzip Project
        run: unzip project.zip -d .

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4 # עודכן ל-v4 כדי לתקן את השגיאה
        with:
          name: my-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
